name: Build and package

on:
    push:
        branches:
            - master
    workflow_dispatch:

permissions:
    contents: read

jobs:
    build:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
        runs-on: ${{ matrix.os }}

        steps:
            - name: Check out project
              uses: actions/checkout@v4

            - name: Set up JDK
              uses: actions/setup-java@v4
              with:
                  distribution: temurin
                  java-version: '21'
                  cache: 'maven'

            - name: Build with Maven
              run: mvn package -Dos=${{ matrix.os }}

            - uses: actions/upload-artifact@v4
              with:
                name: modulegraph-${{ matrix.os }}.zip
                path: target/module*zip
